name: DriftFX Deploy
on:
  workflow_run:
    workflows: ["DriftFX Build"]
    types:
      - completed

jobs:
  notifyJenkins:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo head_branch = ${{ github.event.workflow_run.head_branch }}
        echo head_sha = ${{ github.event.workflow_run.head_sha }}
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.4
    - run: gradle notifyJenkins
      env:
        HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}
        BUILD_RUN_ID: ${{ github.event.workflow_run.id }}
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JENKINS_ACCESS_TOKEN: ${{ secrets.JENKINS_ACCESS_TOKEN }}
